[2023-05-04T04:38:12.914+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: evidently_test_suite.test_suite_html scheduled__2023-05-03T00:00:00+00:00 [queued]>
[2023-05-04T04:38:12.929+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: evidently_test_suite.test_suite_html scheduled__2023-05-03T00:00:00+00:00 [queued]>
[2023-05-04T04:38:12.929+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-05-04T04:38:12.929+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-05-04T04:38:12.929+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-05-04T04:38:12.945+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): test_suite_html> on 2023-05-03 00:00:00+00:00
[2023-05-04T04:38:12.965+0000] {standard_task_runner.py:55} INFO - Started process 89 to run task
[2023-05-04T04:38:12.970+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'evidently_test_suite', 'test_suite_html', 'scheduled__2023-05-03T00:00:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/evidently_test_suite.py', '--cfg-path', '/tmp/tmpjou78o6n']
[2023-05-04T04:38:12.974+0000] {standard_task_runner.py:83} INFO - Job 104: Subtask test_suite_html
[2023-05-04T04:38:13.040+0000] {task_command.py:389} INFO - Running <TaskInstance: evidently_test_suite.test_suite_html scheduled__2023-05-03T00:00:00+00:00 [running]> on host 78523dc16bce
[2023-05-04T04:38:13.108+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=evidently_test_suite
AIRFLOW_CTX_TASK_ID=test_suite_html
AIRFLOW_CTX_EXECUTION_DATE=2023-05-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-03T00:00:00+00:00
[2023-05-04T04:38:14.979+0000] {logging_mixin.py:137} INFO - Creation of the directory reports failed
[2023-05-04T04:38:15.067+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/evidently_test_suite.py", line 72, in test_suite_html_execute
    data_quality_suite.save_html(os.path.join(dir_path, file_path))
  File "/home/airflow/.local/lib/python3.10/site-packages/evidently/suite/base_suite.py", line 137, in save_html
    dashboard_id, dashboard_info, graphs = self._build_dashboard_info()
  File "/home/airflow/.local/lib/python3.10/site-packages/evidently/test_suite/test_suite.py", line 173, in _build_dashboard_info
    test_results.append(renderer.render_html(test))
  File "/home/airflow/.local/lib/python3.10/site-packages/evidently/tests/data_quality_tests.py", line 293, in render_html
    current_correlations = metric_result.current.correlation[method]
KeyError: None
[2023-05-04T04:38:15.078+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=evidently_test_suite, task_id=test_suite_html, execution_date=20230503T000000, start_date=20230504T043812, end_date=20230504T043815
[2023-05-04T04:38:15.094+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 104 for task test_suite_html (None; 89)
[2023-05-04T04:38:15.146+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-05-04T04:38:15.172+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
