[2023-05-04T03:20:35.979+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: train_ml_pipeline.train_model manual__2023-05-04T03:20:16.505818+00:00 [queued]>
[2023-05-04T03:20:35.992+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: train_ml_pipeline.train_model manual__2023-05-04T03:20:16.505818+00:00 [queued]>
[2023-05-04T03:20:35.992+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-05-04T03:20:35.992+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-05-04T03:20:35.992+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-05-04T03:20:36.008+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): train_model> on 2023-05-04 03:20:16.505818+00:00
[2023-05-04T03:20:36.028+0000] {standard_task_runner.py:55} INFO - Started process 142 to run task
[2023-05-04T03:20:36.032+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'train_ml_pipeline', 'train_model', 'manual__2023-05-04T03:20:16.505818+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/machine_learning_trainig_dag_Septembre.py', '--cfg-path', '/tmp/tmpv9s8faot']
[2023-05-04T03:20:36.036+0000] {standard_task_runner.py:83} INFO - Job 50: Subtask train_model
[2023-05-04T03:20:36.099+0000] {task_command.py:389} INFO - Running <TaskInstance: train_ml_pipeline.train_model manual__2023-05-04T03:20:16.505818+00:00 [running]> on host 952e18c165c5
[2023-05-04T03:20:36.164+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=train_ml_pipeline
AIRFLOW_CTX_TASK_ID=train_model
AIRFLOW_CTX_EXECUTION_DATE=2023-05-04T03:20:16.505818+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-04T03:20:16.505818+00:00
[2023-05-04T03:20:36.178+0000] {logging_mixin.py:137} INFO - None
[2023-05-04T03:20:36.179+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script.py", line 46, in train_model
    wandb.login(key=os.environ.get(wandb_api_key))
  File "/usr/local/lib/python3.10/_collections_abc.py", line 819, in get
    return self[key]
  File "/usr/local/lib/python3.10/os.py", line 677, in __getitem__
    value = self._data[self.encodekey(key)]
  File "/usr/local/lib/python3.10/os.py", line 757, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType
[2023-05-04T03:20:36.189+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=train_ml_pipeline, task_id=train_model, execution_date=20230504T032016, start_date=20230504T032035, end_date=20230504T032036
[2023-05-04T03:20:36.203+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 50 for task train_model (str expected, not NoneType; 142)
[2023-05-04T03:20:36.243+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-05-04T03:20:36.271+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
